### PR TITLE
Update lightbox.js

### PR DESCRIPTION
**Pull request by namezero111111**
Fixes thumbnail preview selection for Redmine 3.4

### CODE REVIEW

**Comment by tofi86** [comment]
Can you tell a bit more what this proposed fix is doing?
On which page does it improve thumbnail display?

**Comment by namezero111111** [comment]
In our new Redmine 3.4.4 test environment, the image link here is inside the "div.journal.attachment a" rather than "div.journal div.thumbnails a".
This causes the lightbox to display an error message, because the /download/ part is not subsituted.
untitled

**Comment by namezero111111** [comment]
This occurs if another plugin, redmine_inline_note_images is used. Apparently this has become obsolete with the thumbnail option in Settings->Display.

**Comment by tofi86** [comment]
Alright, thanks anyways for the explanation :-)

**Pull request closed without merging**
